# Official setup:
#   conda env create --prefix ./Environment/ndswin-jax -f environment.yml
#   conda activate ./Environment/ndswin-jax
name: ndswin-jax
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - -e .[dev,training,gpu]
