# Official setup:
#   conda env create --prefix ./Environment/ndswin-jax -f environment.yml
#   conda activate ./Environment/ndswin-jax
name: ndswin-jax
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - nvidia-cuda-nvcc-cu12
  # Minimal environment for HF datasets and JAX
  - pip:
    - -e .
